#! /bin/sh

DAEMON="coffee cluster"
NAME=Accounts9
DESC=Accounts9
PIDFILE="accounts9.pid"

case "$1" in
  start)
        echo "Starting $DESC: "
        NODE_ENV=production nohup $DAEMON > /dev/null &
        echo $! > $PIDFILE
        echo "$NAME."
        ;;
  stop)
        echo "Stopping $DESC: "
        pid=`cat $PIDFILE`
        kill $pid
        rm $PIDFILE
        echo "$NAME."
        ;;
    esac

    exit 0
